# Default values for springboot-mysql-chart.
# This YAML file configures the Spring Boot app and MySQL.

# Spring Boot Application Configuration
replicaCount: 3

# Spring Boot Image Configuration
image:
  repository: vinaylekkalapudii/springboot  # Replace with your Spring Boot Docker image repository
  pullPolicy: IfNotPresent
  tag: ""  # Replace with your Spring Boot image tag (e.g., 'latest' or specific version)

# Secret for pulling from a private repository (optional)
imagePullSecrets: []

# Service Account Configuration (optional)
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Kubernetes Service Configuration for Spring Boot
service:
  type: LoadBalancer
  port: 8080  # Replace with the port your Spring Boot app listens on

# Liveness and Readiness Probes
livenessProbe:
  httpGet:
    path: /health  # Spring Boot default health check endpoint
    port: http
readinessProbe:
  httpGet:
    path: /health  # Spring Boot default health check endpoint
    port: http

# Resource Requests and Limits (optional)
resources: {}

# MySQL Configuration
mysql:
  # MySQL Docker Image Configuration
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: "8.0"  # Replace with the specific version of MySQL you want to use

  # MySQL root user password
  rootPassword: "<your-root-password>"  # Replace with your root password

  # MySQL database name (Spring Boot will connect to this)
  databaseName: springboot_db

  # MySQL Username and Password
  user: springboot_user
  password: "springboot-password"  # Replace with your MySQL user password

  # MySQL Port Configuration (default is 3306)
  port: 3306

  # MySQL Service Configuration
  service:
    type: ClusterIP
    port: 3306

# Ingress Configuration for Spring Boot (optional)
ingress:
  enabled: false  # Set to 'true' if you want to expose Spring Boot via ingress
  className: ""
  annotations: {}
  hosts:
    - host: <your-domain-or-service-name>
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Autoscaling Configuration (optional)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Node Selector, Tolerations, and Affinity (optional)
nodeSelector: {}
tolerations: []
affinity: {}

